# Generated by Django 3.2 on 2021-04-17 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_alter_company_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='favorites',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
